<div class="row">
    <div class="col-12 col-md-6"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_1', true) ?></div>
    <div class="col-12 col-md-2"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_2', true) ?></div>
    <div class="col-12 col-md-2"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_3', true) ?></div>
    <div class="col-12 col-md-2"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_4', true) ?></div>
</div>