<div class="row dnd-plugins-row">
    <div class="col-12 dnd-plugins-col-12 col-md-2 dnd-plugins-col-md-2"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_1', true) ?></div>
    <div class="col-12 dnd-plugins-col-12 col-md-2 dnd-plugins-col-md-2"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_2', true) ?></div>
    <div class="col-12 dnd-plugins-col-12 col-md-8 dnd-plugins-col-md-8"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_3', true) ?></div>
</div>