<div class="row dnd-plugins-row">
    <div class="col-12 dnd-plugins-col-12"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_1', true) ?></div>
</div>
<div class="row dnd-plugins-row">
    <div class="col-12 dnd-plugins-col-12 col-md-4 dnd-plugins-col-md-4"></div>
    <div class="col-12 dnd-plugins-col-12 col-md-4 dnd-plugins-col-md-4"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_2', true) ?></div>
    <div class="col-12 dnd-plugins-col-12 col-md-4 dnd-plugins-col-md-4"></div>
</div>