<div class="row">
    <div class="col-12 col-md-6 dnd-4-cols-3-cols-left-w-1-col-right">
        <div class="row">
            <div class="col-12">
                <?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_2', true) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_3', true) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_4', true) ?>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-6">
        <?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_1', true) ?>
    </div>
</div>