<div class="row dnd-plugins-row">
    <div class="col-12 dnd-plugins-col-12 col-md-3 dnd-plugins-col-md-3"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_1', true) ?></div>
    <div class="col-12 dnd-plugins-col-12 col-md-6 dnd-plugins-col-md-6"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_2', true) ?></div>
    <div class="col-12 dnd-plugins-col-12 col-md-3 dnd-plugins-col-md-3"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_3', true) ?></div>
</div>