<div class="row">
    <div class="col-md-4"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_1') ?></div>
    <div class="col-md-4"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_2') ?></div>
    <div class="col-md-4"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_3') ?></div>
</div>
<div class="row">
    <div class="col-md-12"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_4') ?></div>
</div>