<div class="row">
    <div class="col-12 col-md-3"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_1') ?></div>
    <div class="col-12 col-md-3"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_2') ?></div>
    <div class="col-12 col-md-3"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_3') ?></div>
    <div class="col-12 col-md-3"><?= $this->MelisDragDropZone($this->pageId, $this->dndId . '_4') ?></div>
</div>