<?php
$data_dragdropzone_id = " data-dragdropzone-id='$this->dragdropzoneId'";

$pluginId = '';
if (!empty($this->pluginFrontConfig) && !empty($this->pluginFrontConfig['id']))
    $pluginId = $this->pluginFrontConfig['id'];
?>

<div class="melis-dragdropzone-container" title="<?= $this->dragdropzoneId; ?>"
    data-dragdropzone-id="<?= $this->dragdropzoneId; ?>"
    data-after="<?= $this->dragDropLabel; ?>"
    data-module="<?= $this->configPluginKey; ?>"
    data-plugin="<?= $this->pluginName; ?>"
    data-plugin-id="<?= $pluginId; ?>"
    data-melis-tag="<?= $this->pluginXmlDbKey; ?>"
    data-layout-template="<?= $this->dndLayoutTemplate; ?>"
    data-site-module="<?= $this->siteModule; ?>">
    <div class="dnd-layout-wrapper">
        <div class="dnd-layout-indicator melis-plugin-indicator">
            <i class="fa fa-plug"></i>
        </div>
        <div class="dnd-layout-buttons">
            <div class="m-plugin-sub-tools">
                <div class="m-move-handle">
                    <i class="fa fa-arrows"></i>
                </div>
	        </div>
            <button class="btn dnd-plus-button" data-page-id="<?= $this->pageId; ?>" data-plugin-id="<?= $pluginId ?>">
                <i class="fa fa-plus"></i>
            </button>

            <button type="button" class="btn btn-layout-popover" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-html="true" data-bs-content-id="layout_popover_<?= $pluginId; ?>">
                <i class="fa fa-columns"></i>
            </button>
            <?= $this->partial('MelisFront/dragdropzone/meliscontainer-buttons'); ?>
        </div>
        <div class="<?= $this->hasDragDropZone ? '' : 'melis-dragdropzone' ?> no-content"
            data-dragdropzone-id="<?= $this->dragdropzoneId; ?>"
            data-after="<?= $this->dragDropLabel; ?>"
            data-module="<?= $this->configPluginKey; ?>"
            data-plugin="<?= $this->pluginName; ?>"
            data-plugin-id="<?= $pluginId ?>"
            data-melis-tag="<?= $this->pluginXmlDbKey; ?>"
            data-site-module="<?= $this->siteModule; ?>">
            <?php
                echo $this->viewFront;
            ?>
        </div>
    </div>
</div>