<div class="column-icons">
    <button class="column-icon top-1-col-w-bottom-1-3-center">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
            <div class="icon-row justify-content-center">
                <div class="icon-col-bg icon-col-4 bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon top-1-col-w-center-1-3-center-w-bottom-1-col">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
            <div class="icon-row justify-content-center">
                <div class="icon-col-bg icon-col-4 bg-white"></div>
            </div>
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
        </div>
    </buttton>
    <button class="column-icon whole-1-col">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon half-1-col-left-w-right-2-col">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-6 icon-col-bg bg-white">
                </div>
                <div class="icon-col-6">
                    <div class="icon-row">
                        <div class="icon-col-bg icon-col-12 bg-white"></div>
                    </div>
                    <div class="icon-row">
                        <div class="icon-col-bg icon-col-12 bg-white"></div>
                    </div>
                </div>
            </div>
        </div>
    </button>
    <button class="column-icon left-2-col-w-right-1-col">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-6">
                    <div class="icon-row">
                        <div class="icon-col-bg icon-col-12 bg-white"></div>
                    </div>
                    <div class="icon-row">
                        <div class="icon-col-bg icon-col-12 bg-white"></div>
                    </div>
                </div>
                <div class="icon-col-bg icon-col-6 bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon four-col-equal-square">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col-6 bg-white"></div>
                <div class="icon-col-bg icon-col-6 bg-white"></div>
            </div>
            <div class="icon-row">
                <div class="icon-col-bg icon-col-6 bg-white"></div>
                <div class="icon-col-bg icon-col-6 bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon half-1-col-left-w-right-3-col">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col-6 bg-white"></div>
                <div class="icon-col-bg icon-col-6">
                    <div class="icon-row">
                        <div class="icon-col-bg icon-col-12 bg-white"></div>
                    </div>
                    <div class="icon-row">
                        <div class="icon-col-bg icon-col-12 bg-white"></div>
                    </div>
                    <div class="icon-row">
                        <div class="icon-col-bg icon-col-12 bg-white"></div>
                    </div>
                </div>
            </div>
        </div>
    </button>
    <button class="column-icon left-3-col-w-half-1-col-right">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-6">
                    <div class="icon-row">
                        <div class="icon-col-bg icon-col-12 bg-white"></div>
                    </div>
                    <div class="icon-row">
                        <div class="icon-col-bg icon-col-12 bg-white"></div>
                    </div>
                    <div class="icon-row">
                        <div class="icon-col-bg icon-col-12 bg-white"></div>
                    </div>
                </div>
                <div class="icon-col-bg icon-col-6 bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon top-1-3-col-center">
        <div class="icon-container">
            <div class="icon-row justify-content-center">
                <div class="icon-col-bg icon-col-4 bg-white"></div>
            </div>
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12"></div>
            </div>
        </div>
    </button>
    <button class="column-icon top-1-3-col-center-w-bottom-1-col">
        <div class="icon-container">
            <div class="icon-row justify-content-center">
                <div class="icon-col-bg icon-col-4 bg-white"></div>
            </div>
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon half-col-equal">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col-6 bg-white"></div>
                <div class="icon-col-bg icon-col-6 bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon three-col-equal">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col-4 bg-white"></div>
                <div class="icon-col-bg icon-col-4 bg-white"></div>
                <div class="icon-col-bg icon-col-4 bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon four-col-equal">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col bg-white"></div>
                <div class="icon-col-bg icon-col bg-white"></div>
                <div class="icon-col-bg icon-col bg-white"></div>
                <div class="icon-col-bg icon-col bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon half-col-top-bottom">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
            <div class="icon-row justify-content-center">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon three-col-equal-top-bottom">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
        </div>
    </button>
    <button class="column-icon four-col-equal-top-bottom">
        <div class="icon-container">
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
            <div class="icon-row">
                <div class="icon-col-bg icon-col-12 bg-white"></div>
            </div>
        </div>
    </button>
</div>