<?php
$data_dragdropzone_id = " data-dragdropzone-id='$this->dragdropzoneId'";

$pluginId = '';
if (!empty($this->pluginFrontConfig) && !empty($this->pluginFrontConfig['id']))
    $pluginId = $this->pluginFrontConfig['id'];
?>

<div class="melis-dragdropzone-container"
    data-dragdropzone-id="<?= $this->dragdropzoneId; ?>"
    data-after="<?= $this->dragDropLabel; ?>"
    data-module="<?= $this->configPluginKey; ?>"
    data-plugin="<?= $this->pluginName; ?>"
    data-plugin-id="<?= $pluginId; ?>"
    data-melis-tag="<?= $this->pluginXmlDbKey; ?>"
    data-layout-template="<?= $this->dndLayoutTemplate; ?>"
    data-plugin-referer="<?= $this->dndPluginReferer; ?>"
    data-site-module="<?= $this->siteModule; ?>">
    <div class="dnd-layout-wrapper">
        <div class="dnd-layout-indicator melis-plugin-indicator">
            <img src="/MelisFront/images/icons/dnd-icon.png" alt="dragndrop icon" width="25" height="25" />
        </div>
        <div class="dnd-layout-buttons melis-plugin-tools-box">
            <div class="dnd-plugin-title-and-sub-tools">
                <div class="melis-plugin-title-box">
                    <span class="melis-dnd-title melis-module-title">DND Zone</span>
                    <span class="melis-dnd-sub-title melis-plugin-title">Layout</span>
                </div>
                <div class="dnd-plugin-sub-tools">
                    <button class="btn dnd-plus-button" title="Add dragdropzone below" data-page-id="<?= $this->pageId; ?>" data-dnd-id="<?= $pluginId ?>" data-melis-site="<?= $this->siteModule; ?>">
                        <i class="fa fa-plus"></i>
                    </button>
                    <?php if (!empty($this->dndPluginReferer)) { ?>
                        <button class="btn dnd-remove-button" title="Remove dragdropzone" data-page-id="<?= $this->pageId; ?>" data-dnd-id="<?= $pluginId ?>">
                            <i class="fa fa-trash"></i>
                        </button>
                    <?php } ?>
                    <button class="btn dnd-arrow dnd-arrow-down" title="Swap position of dragdropzone down" data-page-id="<?= $this->pageId; ?>">
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <button class="btn dnd-arrow dnd-arrow-up" title="Swap position of dragdropzone up" data-page-id="<?= $this->pageId; ?>">
                        <i class="fa fa-caret-up"></i>
                    </button>
                </div>
            </div>
            <?= $this->partial('MelisFront/dragdropzone/meliscontainer-buttons'); ?>
        </div>
        <div class="<?= $this->hasDragDropZone ? '' : 'melis-dragdropzone' ?> no-content"
            data-dragdropzone-id="<?= $this->dragdropzoneId; ?>"
            data-after="<?= $this->dragDropLabel; ?>"
            data-module="<?= $this->configPluginKey; ?>"
            data-plugin="<?= $this->pluginName; ?>"
            data-plugin-id="<?= $pluginId ?>"
            data-melis-tag="<?= $this->pluginXmlDbKey; ?>"
            data-site-module="<?= $this->siteModule; ?>">
            <?php
            echo $this->viewFront;
            ?>
        </div>
    </div>
</div>