<?php
$data_dragdropzone_id = " data-dragdropzone-id='$this->dragdropzoneId'";

$pluginId = '';
if (!empty($this->pluginFrontConfig) && !empty($this->pluginFrontConfig['id']))
    $pluginId = $this->pluginFrontConfig['id'];
?>

<div class="melis-dragdropzone-container"
    data-dragdropzone-id="<?= $this->dragdropzoneId; ?>"
    data-after="<?= $this->dragDropLabel; ?>"
    data-module="<?= $this->configPluginKey; ?>"
    data-plugin="<?= $this->pluginName; ?>"
    data-plugin-id="<?= $pluginId; ?>"
    data-melis-tag="<?= $this->pluginXmlDbKey; ?>"
    data-layout-template="<?= $this->dndLayoutTemplate; ?>"
    data-plugin-referer="<?= $this->dndPluginReferer; ?>"
    data-site-module="<?= $this->siteModule; ?>">
    <div class="dnd-layout-wrapper">
        <div class="dnd-layout-indicator melis-plugin-indicator">
            <button class="column-icon half-1-col-left-w-right-2-col">
                <div class="icon-container">
                    <div class="icon-row">
                        <div class="icon-col-6 icon-col-bg bg-white">
                        </div>
                        <div class="icon-col-6">
                            <div class="icon-row">
                                <div class="icon-col-bg icon-col-12 bg-white"></div>
                            </div>
                            <div class="icon-row">
                                <div class="icon-col-bg icon-col-12 bg-white"></div>
                            </div>
                        </div>	
                    </div>
                </div>
            </button>
        </div>
        <div class="dnd-layout-buttons melis-plugin-tools-box">
            <div class="dnd-plugin-title-and-sub-tools">
                <div class="melis-plugin-title-box">
                    <span class="melis-dnd-title melis-module-title">DND Zone</span>
                    <span class="melis-dnd-sub-title melis-plugin-title">Layout</span>
                </div>
                <div class="dnd-plugin-sub-tools">
                    <div class="dnd-plus-remove-buttons">
                        <button class="btn dnd-plus-button" title="<?= $this->translate('tr_melis_front_dnd_add_button_title')?>" data-page-id="<?= $this->pageId; ?>" data-dnd-id="<?= $pluginId ?>" data-melis-site="<?= $this->siteModule; ?>">
                            <i class="fa fa-plus"></i>
                        </button>
                        <?php if (!empty($this->dndPluginReferer)) { ?>
                            <button class="btn dnd-remove-button" title="<?= $this->translate('tr_melis_front_dnd_remove_button_title')?>" data-page-id="<?= $this->pageId; ?>" data-dnd-id="<?= $pluginId ?>">
                                <i class="fa fa-trash"></i>
                            </button>
                        <?php } ?>
                    </div>
                    <div class="dnd-arrow-buttons">
                        <button class="btn dnd-arrow dnd-arrow-down" title="<?= $this->translate('tr_melis_front_dnd_arrow_down_button_title')?>" data-page-id="<?= $this->pageId; ?>">
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <button class="btn dnd-arrow dnd-arrow-up" title="<?= $this->translate('tr_melis_front_dnd_arrow_up_button_title')?>" data-page-id="<?= $this->pageId; ?>">
                            <i class="fa fa-caret-up"></i>
                        </button>
                    </div>
                </div>
            </div>
            <?= $this->partial('MelisFront/dragdropzone/meliscontainer-buttons'); ?>
        </div>
        <div class="<?= $this->hasDragDropZone ? '' : 'melis-dragdropzone' ?> no-content"
            data-dragdropzone-id="<?= $this->dragdropzoneId; ?>"
            data-after="<?= $this->dragDropLabel; ?>"
            data-module="<?= $this->configPluginKey; ?>"
            data-plugin="<?= $this->pluginName; ?>"
            data-plugin-id="<?= $pluginId ?>"
            data-melis-tag="<?= $this->pluginXmlDbKey; ?>"
            data-site-module="<?= $this->siteModule; ?>">
            <?php
            echo $this->viewFront;
            ?>
        </div>
    </div>
</div>