<div id="layout_popover_<?= $this->dragdropzoneId; ?>" class="layout-popover">
    <header class="d-flex flex-row justify-content-between">
        <h5>Column Layout</h5>
        <button type="button" class="btn close-btn"><i class="fa fa-times"></i></button>
    </header>
    <div class="column-icons">
        <?php
            foreach ($this->dndLayouts as $k => $layout) {
                // dump($layout);
                if (!empty($layout['template']) && (!empty($layout['html-button-icon'])))
                    echo '<div data-dnd-id="' . $this->dndId . '" data-dnd-tpl="' . $k . '" data-page-id="' . $this->pageId . '" data-melis-site="' . $_GET['melisSite'] . '">' . $layout['html-button-icon'] . '</div>';
            }
        ?>
    </div>
</div>