<div class="revalidation-plugin text-center" style="float:none;">
    <?php
    /**
     * we show the form only for those user's days inactive was already passed
     */
    ?>
    <?php if (!$this->userStillActive) { ?>
        <?php if (!$this->isRevalidated) { ?>
            <?php if (!empty($this->userData)) { ?>
                <p class="revalidation-info">You subscription to our services must be revalidated according to the GDPR
                    requirements as you have not been active for a long time. Failure to revalidate will automatically
                    activate the suppression of your account.</p>
                <?php
                $this->revalidationForm->prepare();
                echo $this->form()->openTag($this->revalidationForm);
                echo $this->formCollection($this->revalidationForm);
                ?>
                <button class="btn btn-success btn-lg" type="submit">Confirm</button>
                <?= $this->form()->closeTag(); ?>
            <?php } else { ?>
                <div class="alert alert-warning">
                    <p>This link doesn’t seem to work or is not recognized.</p>
                </div>
            <?php } ?>
        <?php } else { ?>
            <div class="alert alert-success">
                <h4>Well done !</h4>
                <p>Your account is now up to date !</p>
            </div>
        <?php } ?>
    <?php } else {?>
        <div class="alert alert-warning">
            <p>This link doesn’t seem to work or is not recognized.</p>
        </div>
    <?php }?>
</div>