<?php
	// Make a list from an array
	function makeList($array) 
	{
	    
		// Base case: an empty array produces no list
		if (empty($array))
		{
		    return '';
		}
		
		// Recursive Step: make a list with child lists
		$output = '<ul>'.PHP_EOL;
		
		foreach ($array as $key => $subArray) 
		{
		    $subMenu = (!empty($subArray['pages'])) ? makeList($subArray['pages']) : PHP_EOL;
			$output .= '<li>' . $subArray['label'] . $subMenu . '</li>'.PHP_EOL;
		}
		
		$output .= '</ul>'.PHP_EOL;
		
		return $output;
	}
	
	if ($this->menu)
	{
	    echo makeList($this->menu);
	}
	else
	{
	    echo '<div class="alert alert-warning" role="alert">No result</div>';
	}
?>