<?php
	// Make a list from an array
	function makeListFold($array) 
	{
	    
		// Base case: an empty array produces no list
		if (empty($array))
		{
		    return '';
		}
		
		// Recursive Step: make a list with child lists
		$output = '<ul>'.PHP_EOL;
		
		foreach ($array as $key => $subArray) 
		{
		    $subMenu = (!empty($subArray->children)) ? makeListFold($subArray->children) : PHP_EOL;
			$output .= '<li>' . $subArray->page_name . $subMenu . '</li>'.PHP_EOL;
		}
		
		$output .= '</ul>'.PHP_EOL;
		
		return $output;
	}
	
	if ($this->listofpages)
	{
	    echo makeListFold($this->listofpages);
	}
	else
	{
	    echo '<div class="alert alert-warning" role="alert">No result</div>';
	}
?>